[package]
name = "spotcheck"
version = "0.1.0"
authors = ["Altug Sahin <altugsahin@gmail.com>"]
edition = "2018"


[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
tokio = { version = "0.2", features = ["full"] }
scraper = "0.11.0"
select = "0.4.3"
regex = "1.3.7"
